### ISSUE TITLE
Housing Cover Gasket / Sealing Detail

### ISSUE THREAD

**Issue by mtfunder** [precision-sustainable-ag/psa-planning#202]
## Rationale ##
- The housing lid will need a gasket, Oring, or similar to seal against water / dust intrusion.

## What done looks like ##
- All new parts added to PartsBox
- Confluence page updated to reflect the design decisions.

## Stakeholders / Contacts ##
- @mtfunder 

## Additional Information ##
- Keep manufacturability in mind, we want this assembly to be straightforward.
- Adhere to best practices with sizing of groves and radii.
- Use standard components where possible.

**Comment by rbabcoc** [comment]
After sanity checking my initial design with Alex, I feel that the current groove for the O-ring should be sufficient, however, I'll read up on the Park O-Ring Handbook to ensure that I have the right sizing and compression on the ring

**Comment by mtfunder** [comment]
@rbabcoc In the future move tasks to "In Review" rather than "done", unless you created them for yourself.

Is there a link to the confluence page where you put the information on this?
