### ISSUE TITLE
Recreate existing take action site in GROW

### ISSUE THREAD

**Issue by Adamws33** [precision-sustainable-ag/psa-planning#37]
## Rationale ##
We recently received a grant to migrate take action into the GROW site.

## Owner ##
@Adamws33 

## Stakeholder Point of Contact ##
@EmilyUnglesbee 

## Description ##
After taking over the grow site from first Accent there were a list of updates they could not complete or did not get to.  

## Issues ##

- [x] https://github.com/precision-sustainable-ag/grow-wordpress/issues/6
- [x] https://github.com/precision-sustainable-ag/grow-wordpress/issues/21
- [x] https://github.com/precision-sustainable-ag/grow-wordpress/issues/33
- [x] https://github.com/precision-sustainable-ag/grow-wordpress/issues/34

**Comment by mikahpinegar** [comment]
@Adamws33 can you split this into two epics? one for take action ingestion and one for grow updates v2?
